
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
    name: nginx
spec:
  replicas: 25
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      labels:
        app: myapp
        type: front-end
        name: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.30-Err
